### ISSUE TITLE
Research AWS Vs Google Cloud Vs Docker

### ISSUE THREAD

**Issue by helenijevans** [be-betta/be-betta#3]
@normansophie789 @helenijevans

**Comment by normansophie789** [comment]
Could also consider things like Docker

**Comment by helenijevans** [comment]
> Could also consider things like Docker

add it to the title?

**Comment by normansophie789** [comment]
Also GitHub Actions and Continuous Integration?

**Comment by helenijevans** [comment]
> Also GitHub Actions and Continuous Integration?

no thank you
